version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  slack: circleci/slack@4.4.2

jobs:
  run_automation:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    parameters:
      execution_type:
        type: string
      tag:
        type: string
      browser:
        type: string
      env_profile:
        type: string
      threads:
        type: string
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Running rake command
          command: bundle exec rake "parallel_tests_circle_ci[<<parameters.tag>>, <<parameters.browser>>, <<parameters.env_profile>>, <<parameters.threads>>, ${CIRCLE_BUILD_NUM}]"
      - store_artifacts:
          path: reports/final_reports
          destination: parallel_report
      - slack/notify:
          event: fail
          mentions: '@Francisco Santos'
          custom: |
            {
            "blocks": [
            {
            "type": "section",
            "fields": [
              {
                "type": "plain_text",
                "text": ":x: Ops, one or more tests have failed! :x: \n \n :skull_and_crossbones: :no_entry_sign: :warning:",
                "emoji": true
              }
            ]
            },
            {
            "type": "section",
            "fields": [
              {
                "type": "plain_text",
                "text": "AUTOMATION RESULTS - BUILD: ${CIRCLE_BUILD_NUM} \n \n BROWSER: <<parameters.browser>> \n \n SCOPE: <<parameters.tag>>",
                "emoji": true
              }
            ]
            },
            {
            "type": "actions",
            "elements": [
              {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Test Report",
                  "emoji": true
                },
                "value": "Access test report",
                "url": "https://app.circleci.com/pipelines/github/lvieira2308/poc_inkblot-therapy/1/workflows/${CIRCLE_WORKFLOW_ID}/jobs/${CIRCLE_BUILD_NUM}/artifacts"
              }
            ]
            },
            {
              "type": "divider"
            }
            ]
            }
      - slack/notify:
          event: pass
          mentions: '@Luis Vieira'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": ":white_check_mark: All tests have passed successfully! :white_check_mark: \n \n :partying_face: :tada: :confetti_ball: \n \n \n",
                      "emoji": true
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "AUTOMATION RESULTS - BUILD: ${CIRCLE_BUILD_NUM} \n \n BROWSER: <<parameters.browser>> \n \n SCOPE: <<parameters.tag>>",
                      "emoji": true
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Test Report",
                        "emoji": true
                      },
                      "value": "Access test report",
                      "url": "https://app.circleci.com/pipelines/github/lvieira2308/poc_inkblot-therapy/143/workflows/${CIRCLE_WORKFLOW_ID}/jobs/${CIRCLE_BUILD_NUM}/artifacts"
                    }
                  ]
                },
                {
                    "type": "divider"
                }
              ]
            }

parameters:
  execution_type:
    type: string
    default: "On Demand"
  tag:
    type: string
    default: ""
  browser:
    type: string
    default: ""
  env_profile:
    type: string
    default: ""
  threads:
    type: string
    default: "1"
  run_workflow_ondemand:
    default: false
    type: boolean

workflows:
  version: 2.1
  run_automation:
    when: << pipeline.parameters.run_workflow_ondemand >>
    jobs:
      - run_automation:
          execution_type: <<pipeline.parameters.execution_type>>
          tag: <<pipeline.parameters.tag>>
          browser: <<pipeline.parameters.browser>>
          env_profile: <<pipeline.parameters.env_profile>>
          threads: <<pipeline.parameters.threads>>
          filters:
            branches:
              only:
                - feature/develop
  Android-Payment-Schedule:
    triggers:
      - schedule:
          cron: "0 9,13,18,21 * * *"
          filters:
            branches:
              only:
                - feature/develop
    jobs:
      - run_automation:
          execution_type: "Schedule"
          tag: "@poc"
          browser: "chrome"
          env_profile: "stg_t"
          threads: "1"


