name: Ruby

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.124.0
        with:
          ruby-version: '2.7' # Not needed with a .ruby-version file
          bundler-cache: true
      - run: bundle exec rake "parallel_tests_circle_ci[@poc, chrome, stg_t, 1, jira-IQ-2, $GITHUB_RUN_NUMBER]"